on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 arm64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: |
            oracle
#            liberica
          architecture: 'aarch64'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true
      - name: Package
        run: |
          sh package-ci.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: Luyten-1.7.0.dmg
          if-no-files-found: error
          overwrite: true
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "Luyten-1.7.0.dmg"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}