name: Build Luyten
run-name: ${{ github.actor }} Build Luyten
on:
  push:
    tags:
      - v1.*
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [ 'aarch64', 'x64' ]
    name: Luyten ${{ matrix.architecture }} dmg
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 arm64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: |
            oracle
#            liberica
          architecture: ${{ matrix.architecture }}
          cache: maven
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true
      - name: Package
        run: |
          v=${{ github.ref_name }}
          v=$(echo ${v/v/''})
          sh package-ci.sh $v ${{ github.ref_name }} ${{ matrix.architecture }}
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: Package
      #     path: Luyten-1.0.0.dmg
      #     if-no-files-found: error
      #     overwrite: true
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "Luyten-${{ github.ref_name }}-${{ matrix.architecture }}.dmg"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}